CREATE DATABASE IF NOT EXISTS smartverbs_db;
USE smartverbs_db;

-- Création de la table des utilisateurs
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    stats_json TEXT
);

-- Création de la table des verbes irréguliers
CREATE TABLE IF NOT EXISTS verbs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fr VARCHAR(100) UNIQUE NOT NULL,
    base VARCHAR(100) NOT NULL,
    past VARCHAR(100) NOT NULL,
    participle VARCHAR(100) NOT NULL,
    past_alt VARCHAR(100) DEFAULT NULL,
    participle_alt VARCHAR(100) DEFAULT NULL
);

INSERT INTO verbs (fr, base, past, participle, past_alt, participle_alt) VALUES
('être', 'be', 'was', 'been', 'were', NULL),
('battre', 'beat', 'beat', 'beaten', NULL, NULL),
('devenir', 'become', 'became', 'become', NULL, NULL),
('commencer', 'begin', 'began', 'begun', NULL, NULL),
('mordre', 'bite', 'bit', 'bitten', NULL, NULL),
('souffler', 'blow', 'blew', 'blown', NULL, NULL),
('casser', 'break', 'broke', 'broken', NULL, NULL),
('apporter', 'bring', 'brought', 'brought', NULL, NULL),
('construire', 'build', 'built', 'built', NULL, NULL),
('acheter', 'buy', 'bought', 'bought', NULL, NULL),
('attraper', 'catch', 'caught', 'caught', NULL, NULL),
('choisir', 'choose', 'chose', 'chosen', NULL, NULL),
('venir', 'come', 'came', 'come', NULL, NULL),
('coûter', 'cost', 'cost', 'cost', NULL, NULL),
('couper', 'cut', 'cut', 'cut', NULL, NULL),
('faire', 'do', 'did', 'done', NULL, NULL),
('dessiner', 'draw', 'drew', 'drawn', NULL, NULL),
('boire', 'drink', 'drank', 'drunk', NULL, NULL),
('conduire', 'drive', 'drove', 'driven', NULL, NULL),
('manger', 'eat', 'ate', 'eaten', NULL, NULL),
('tomber', 'fall', 'fell', 'fallen', NULL, NULL),
('ressentir', 'feel', 'felt', 'felt', NULL, NULL),
('trouver', 'find', 'found', 'found', NULL, NULL),
('voler (dans les airs)', 'fly', 'flew', 'flown', NULL, NULL),
('oublier', 'forget', 'forgot', 'forgotten', NULL, NULL),
('obtenir', 'get', 'got', 'gotten', NULL, 'got'),
('donner', 'give', 'gave', 'given', NULL, NULL),
('aller', 'go', 'went', 'gone', NULL, NULL),
('grandir', 'grow', 'grew', 'grown', NULL, NULL),
('avoir', 'have', 'had', 'had', NULL, NULL),
('entendre', 'hear', 'heard', 'heard', NULL, NULL),
('cacher', 'hide', 'hid', 'hidden', NULL, NULL),
('frapper', 'hit', 'hit', 'hit', NULL, NULL),
('tenir', 'hold', 'held', 'held', NULL, NULL),
('blesser', 'hurt', 'hurt', 'hurt', NULL, NULL),
('garder', 'keep', 'kept', 'kept', NULL, NULL),
('savoir', 'know', 'knew', 'known', NULL, NULL),
('apprendre', 'learn', 'learnt', 'learnt', 'learned', 'learned'),
('quitter / laisser', 'leave', 'left', 'left', NULL, NULL),
('perdre', 'lose', 'lost', 'lost', NULL, NULL),
('faire / fabriquer', 'make', 'made', 'made', NULL, NULL),
('signifier', 'mean', 'meant', 'meant', NULL, NULL),
('rencontrer', 'meet', 'met', 'met', NULL, NULL),
('payer', 'pay', 'paid', 'paid', NULL, NULL),
('mettre', 'put', 'put', 'put', NULL, NULL),
('lire', 'read', 'read', 'read', NULL, NULL),
('monter / s\'élever', 'rise', 'rose', 'risen', NULL, NULL),
('courir', 'run', 'ran', 'run', NULL, NULL),
('dire', 'say', 'said', 'said', NULL, NULL),
('voir', 'see', 'saw', 'seen', NULL, NULL),
('vendre', 'sell', 'sold', 'sold', NULL, NULL),
('envoyer', 'send', 'sent', 'sent', NULL, NULL),
('montrer', 'show', 'showed', 'shown', NULL, NULL),
('fermer', 'shut', 'shut', 'shut', NULL, NULL),
('chanter', 'sing', 'sang', 'sung', NULL, NULL),
('s\'asseoir', 'sit', 'sat', 'sat', NULL, NULL),
('dormir', 'sleep', 'slept', 'slept', NULL, NULL),
('parler', 'speak', 'spoke', 'spoken', NULL, NULL),
('dépenser / passer du temps', 'spend', 'spent', 'spent', NULL, NULL),
('se tenir debout', 'stand', 'stood', 'stood', NULL, NULL),
('voler (dérober)', 'steal', 'stole', 'stolen', NULL, NULL),
('nager', 'swim', 'swam', 'swum', NULL, NULL),
('prendre', 'take', 'took', 'taken', NULL, NULL),
('enseigner', 'teach', 'taught', 'taught', NULL, NULL),
('raconter / dire', 'tell', 'told', 'told', NULL, NULL),
('penser', 'think', 'thought', 'thought', NULL, NULL),
('jeter', 'throw', 'threw', 'thrown', NULL, NULL),
('comprendre', 'understand', 'understood', 'understood', NULL, NULL),
('se réveiller', 'wake', 'woke', 'woken', NULL, NULL),
('porter (un vêtement)', 'wear', 'wore', 'worn', NULL, NULL),
('gagner', 'win', 'won', 'won', NULL, NULL),
('écrire', 'write', 'wrote', 'written', NULL, NULL);INSERT INTO verbs (fr, base, past, participle, past_alt, participle_alt) VALUES
('être', 'be', 'was', 'been', 'were', NULL),
('battre', 'beat', 'beat', 'beaten', NULL, NULL),
('devenir', 'become', 'became', 'become', NULL, NULL),
('commencer', 'begin', 'began', 'begun', NULL, NULL),
('mordre', 'bite', 'bit', 'bitten', NULL, NULL),
('souffler', 'blow', 'blew', 'blown', NULL, NULL),
('casser', 'break', 'broke', 'broken', NULL, NULL),
('apporter', 'bring', 'brought', 'brought', NULL, NULL),
('construire', 'build', 'built', 'built', NULL, NULL),
('acheter', 'buy', 'bought', 'bought', NULL, NULL),
('attraper', 'catch', 'caught', 'caught', NULL, NULL),
('choisir', 'choose', 'chose', 'chosen', NULL, NULL),
('venir', 'come', 'came', 'come', NULL, NULL),
('coûter', 'cost', 'cost', 'cost', NULL, NULL),
('couper', 'cut', 'cut', 'cut', NULL, NULL),
('faire', 'do', 'did', 'done', NULL, NULL),
('dessiner', 'draw', 'drew', 'drawn', NULL, NULL),
('boire', 'drink', 'drank', 'drunk', NULL, NULL),
('conduire', 'drive', 'drove', 'driven', NULL, NULL),
('manger', 'eat', 'ate', 'eaten', NULL, NULL),
('tomber', 'fall', 'fell', 'fallen', NULL, NULL),
('ressentir', 'feel', 'felt', 'felt', NULL, NULL),
('trouver', 'find', 'found', 'found', NULL, NULL),
('voler (dans les airs)', 'fly', 'flew', 'flown', NULL, NULL),
('oublier', 'forget', 'forgot', 'forgotten', NULL, NULL),
('obtenir', 'get', 'got', 'gotten', NULL, 'got'),
('donner', 'give', 'gave', 'given', NULL, NULL),
('aller', 'go', 'went', 'gone', NULL, NULL),
('grandir', 'grow', 'grew', 'grown', NULL, NULL),
('avoir', 'have', 'had', 'had', NULL, NULL),
('entendre', 'hear', 'heard', 'heard', NULL, NULL),
('cacher', 'hide', 'hid', 'hidden', NULL, NULL),
('frapper', 'hit', 'hit', 'hit', NULL, NULL),
('tenir', 'hold', 'held', 'held', NULL, NULL),
('blesser', 'hurt', 'hurt', 'hurt', NULL, NULL),
('garder', 'keep', 'kept', 'kept', NULL, NULL),
('savoir', 'know', 'knew', 'known', NULL, NULL),
('apprendre', 'learn', 'learnt', 'learnt', 'learned', 'learned'),
('quitter / laisser', 'leave', 'left', 'left', NULL, NULL),
('perdre', 'lose', 'lost', 'lost', NULL, NULL),
('faire / fabriquer', 'make', 'made', 'made', NULL, NULL),
('signifier', 'mean', 'meant', 'meant', NULL, NULL),
('rencontrer', 'meet', 'met', 'met', NULL, NULL),
('payer', 'pay', 'paid', 'paid', NULL, NULL),
('mettre', 'put', 'put', 'put', NULL, NULL),
('lire', 'read', 'read', 'read', NULL, NULL),
('monter / s\'élever', 'rise', 'rose', 'risen', NULL, NULL),
('courir', 'run', 'ran', 'run', NULL, NULL),
('dire', 'say', 'said', 'said', NULL, NULL),
('voir', 'see', 'saw', 'seen', NULL, NULL),
('vendre', 'sell', 'sold', 'sold', NULL, NULL),
('envoyer', 'send', 'sent', 'sent', NULL, NULL),
('montrer', 'show', 'showed', 'shown', NULL, NULL),
('fermer', 'shut', 'shut', 'shut', NULL, NULL),
('chanter', 'sing', 'sang', 'sung', NULL, NULL),
('s\'asseoir', 'sit', 'sat', 'sat', NULL, NULL),
('dormir', 'sleep', 'slept', 'slept', NULL, NULL),
('parler', 'speak', 'spoke', 'spoken', NULL, NULL),
('dépenser / passer du temps', 'spend', 'spent', 'spent', NULL, NULL),
('se tenir debout', 'stand', 'stood', 'stood', NULL, NULL),
('voler (dérober)', 'steal', 'stole', 'stolen', NULL, NULL),
('nager', 'swim', 'swam', 'swum', NULL, NULL),
('prendre', 'take', 'took', 'taken', NULL, NULL),
('enseigner', 'teach', 'taught', 'taught', NULL, NULL),
('raconter / dire', 'tell', 'told', 'told', NULL, NULL),
('penser', 'think', 'thought', 'thought', NULL, NULL),
('jeter', 'throw', 'threw', 'thrown', NULL, NULL),
('comprendre', 'understand', 'understood', 'understood', NULL, NULL),
('se réveiller', 'wake', 'woke', 'woken', NULL, NULL),
('porter (un vêtement)', 'wear', 'wore', 'worn', NULL, NULL),
('gagner', 'win', 'won', 'won', NULL, NULL),
('écrire', 'write', 'wrote', 'written', NULL, NULL);

