const irregularVerbs = [
    { fr: "être", base: "be", past: "was", participle: "been", pastAlt: "were" },
    { fr: "battre", base: "beat", past: "beat", participle: "beaten" },
    { fr: "devenir", base: "become", past: "became", participle: "become" },
    { fr: "commencer", base: "begin", past: "began", participle: "begun" },
    { fr: "mordre", base: "bite", past: "bit", participle: "bitten" },
    { fr: "souffler", base: "blow", past: "blew", participle: "blown" },
    { fr: "casser", base: "break", past: "broke", participle: "broken" },
    { fr: "apporter", base: "bring", past: "brought", participle: "brought" },
    { fr: "construire", base: "build", past: "built", participle: "built" },
    { fr: "acheter", base: "buy", past: "bought", participle: "bought" },
    { fr: "attraper", base: "catch", past: "caught", participle: "caught" },
    { fr: "choisir", base: "choose", past: "chose", participle: "chosen" },
    { fr: "venir", base: "come", past: "came", participle: "come" },
    { fr: "coûter", base: "cost", past: "cost", participle: "cost" },
    { fr: "couper", base: "cut", past: "cut", participle: "cut" },
    { fr: "faire", base: "do", past: "did", participle: "done" },
    { fr: "dessiner", base: "draw", past: "drew", participle: "drawn" },
    { fr: "boire", base: "drink", past: "drank", participle: "drunk" },
    { fr: "conduire", base: "drive", past: "drove", participle: "driven" },
    { fr: "manger", base: "eat", past: "ate", participle: "eaten" },
    { fr: "tomber", base: "fall", past: "fell", participle: "fallen" },
    { fr: "ressentir", base: "feel", past: "felt", participle: "felt" },
    { fr: "trouver", base: "find", past: "found", participle: "found" },
    { fr: "voler (dans les airs)", base: "fly", past: "flew", participle: "flown" },
    { fr: "oublier", base: "forget", past: "forgot", participle: "forgotten" },
    { fr: "obtenir", base: "get", past: "got", participle: "gotten", participleAlt: "got" },
    { fr: "donner", base: "give", past: "gave", participle: "given" },
    { fr: "aller", base: "go", past: "went", participle: "gone" },
    { fr: "grandir", base: "grow", past: "grew", participle: "grown" },
    { fr: "avoir", base: "have", past: "had", participle: "had" },
    { fr: "entendre", base: "hear", past: "heard", participle: "heard" },
    { fr: "cacher", base: "hide", past: "hid", participle: "hidden" },
    { fr: "frapper", base: "hit", past: "hit", participle: "hit" },
    { fr: "tenir", base: "hold", past: "held", participle: "held" },
    { fr: "blesser", base: "hurt", past: "hurt", participle: "hurt" },
    { fr: "garder", base: "keep", past: "kept", participle: "kept" },
    { fr: "savoir", base: "know", past: "knew", participle: "known" },
    { fr: "apprendre", base: "learn", past: "learnt", participle: "learnt", pastAlt: "learned", participleAlt: "learned" },
    { fr: "quitter / laisser", base: "leave", past: "left", participle: "left" },
    { fr: "perdre", base: "lose", past: "lost", participle: "lost" },
    { fr: "faire / fabriquer", base: "make", past: "made", participle: "made" },
    { fr: "signifier", base: "mean", past: "meant", participle: "meant" },
    { fr: "rencontrer", base: "meet", past: "met", participle: "met" },
    { fr: "payer", base: "pay", past: "paid", participle: "paid" },
    { fr: "mettre", base: "put", past: "put", participle: "put" },
    { fr: "lire", base: "read", past: "read", participle: "read" },
    { fr: "monter / s'élever", base: "rise", past: "rose", participle: "risen" },
    { fr: "courir", base: "run", past: "ran", participle: "run" },
    { fr: "dire", base: "say", past: "said", participle: "said" },
    { fr: "voir", base: "see", past: "saw", participle: "seen" },
    { fr: "vendre", base: "sell", past: "sold", participle: "sold" },
    { fr: "envoyer", base: "send", past: "sent", participle: "sent" },
    { fr: "montrer", base: "show", past: "showed", participle: "shown" },
    { fr: "fermer", base: "shut", past: "shut", participle: "shut" },
    { fr: "chanter", base: "sing", past: "sang", participle: "sung" },
    { fr: "s'asseoir", base: "sit", past: "sat", participle: "sat" },
    { fr: "dormir", base: "sleep", past: "slept", participle: "slept" },
    { fr: "parler", base: "speak", past: "spoke", participle: "spoken" },
    { fr: "dépenser / passer du temps", base: "spend", past: "spent", participle: "spent" },
    { fr: "se tenir debout", base: "stand", past: "stood", participle: "stood" },
    { fr: "voler (dérober)", base: "steal", past: "stole", participle: "stolen" },
    { fr: "nager", base: "swim", past: "swam", participle: "swum" },
    { fr: "prendre", base: "take", past: "took", participle: "taken" },
    { fr: "enseigner", base: "teach", past: "taught", participle: "taught" },
    { fr: "raconter / dire", base: "tell", past: "told", participle: "told" },
    { fr: "penser", base: "think", past: "thought", participle: "thought" },
    { fr: "jeter", base: "throw", past: "threw", participle: "thrown" },
    { fr: "comprendre", base: "understand", past: "understood", participle: "understood" },
    { fr: "se réveiller", base: "wake", past: "woke", participle: "woken" },
    { fr: "porter (un vêtement)", base: "wear", past: "wore", participle: "worn" },
    { fr: "gagner", base: "win", past: "won", participle: "won" },
    { fr: "écrire", base: "write", past: "wrote", participle: "written" }
];
